import type { PrismaClient } from 'src/generated/prisma/client';

export async function seedClientes(prisma: PrismaClient) {
    const clientes: Awaited<ReturnType<typeof prisma.clientes.findUnique>>[] = [];

    // 144 estudiantes de SOFTWARE - MATRIZ
    const estudiantesSoftware = [
        { identificacion: "2450524562", nombres: "EDER ANDRES", apellidos: "ALAVA ASENCIO" },
        { identificacion: "2450014242", nombres: "JEAN CARLOS", apellidos: "ALEJANDRO DE LA CRUZ" },
        { identificacion: "2400143307", nombres: "ELKIN WILSON", apellidos: "ALEJANDRO DOMINGUEZ" },
        { identificacion: "2450284290", nombres: "ANDY BRYAN", apellidos: "ALEJANDRO VERA" },
        { identificacion: "2450590761", nombres: "HELEN NOEMI", apellidos: "ALFONZO LOOR" },
        { identificacion: "0928014091", nombres: "MARCOS JOEL", apellidos: "ALTAMIRANO ESCOBAR" },
        { identificacion: "2400453748", nombres: "SKAY GISELL", apellidos: "ALVARADO RODRIGUEZ" },
        { identificacion: "2400180259", nombres: "THIAGO JAMES", apellidos: "AMORES BARZOLA" },
        { identificacion: "2400423675", nombres: "ISMAEL JAREK", apellidos: "ANCHUNDIA CATUTO" },
        { identificacion: "0944288513", nombres: "LUIS ALFREDO", apellidos: "ANCHUNDIA CRUZ" },
        { identificacion: "2450391848", nombres: "GREGORI RAUL", apellidos: "BALON MAGALLAN" },
        { identificacion: "2450880337", nombres: "DEREK DAMIAN", apellidos: "BAQUE HERNANDEZ" },
        { identificacion: "0941380164", nombres: "KAREN LISSETTE", apellidos: "BARRERA PALACIOS" },
        { identificacion: "2400048142", nombres: "JIMMY DANIEL", apellidos: "BAZAN RICARDO" },
        { identificacion: "0928273127", nombres: "KLEBER STEVEN", apellidos: "BELTRAN SALINAS" },
        { identificacion: "2400180093", nombres: "EMERSON JOHAN", apellidos: "BELTRAN SUAREZ" },
        { identificacion: "2450118084", nombres: "GINO MAXIMILIANO", apellidos: "BERMUDEZ SANTOS" },
        { identificacion: "2450608415", nombres: "CARLOS DANIEL", apellidos: "BERNABE BORBOR" },
        { identificacion: "0927157388", nombres: "GEORGE JOFFRE", apellidos: "BRAVO MORAN" },
        { identificacion: "0928015072", nombres: "DONOVAN JARED", apellidos: "CARPIO JUNQUI" },
        { identificacion: "2450619685", nombres: "DAVE JAIRO", apellidos: "CARVAJAL GONZALEZ" },
        { identificacion: "2400245763", nombres: "JEAN PIERRE", apellidos: "CEDEÑO ANDRADE" },
        { identificacion: "2450613175", nombres: "JIM MIKE", apellidos: "CHAMBA RETETE" },
        { identificacion: "2450496787", nombres: "MARIUXI MAGDALENA", apellidos: "CHAVEZ MERCHAN" },
        { identificacion: "0504425851", nombres: "MICHAEL STEEVEN", apellidos: "CHICAIZA CHIMBORAZO" },
        { identificacion: "2400319709", nombres: "KATIUSKA ESTEFANIA", apellidos: "CHOEZ REYES" },
        { identificacion: "2400227662", nombres: "TAMARA ALEJANDRA", apellidos: "CHUEZ SANCHEZ" },
        { identificacion: "2450523663", nombres: "EVELYN YARITZA", apellidos: "CONFORME CHOEZ" },
        { identificacion: "0952838647", nombres: "JOSUE XAVIER", apellidos: "CORNEJO FRANCO" },
        { identificacion: "2450493230", nombres: "JEAN PIERRE", apellidos: "CORREA ASENCIO" },
        { identificacion: "0928239599", nombres: "LUIS ANGEL", apellidos: "CRESPIN LUCAS" },
        { identificacion: "2400401804", nombres: "EMILY GABRIELA", apellidos: "CRUZ NARVAEZ" },
        { identificacion: "0942980509", nombres: "JOSE ANDRES", apellidos: "DE LA A CEDEÑO" },
        { identificacion: "2400181729", nombres: "ESTEFANY SUGGEIDY", apellidos: "DE LA A POZO" },
        { identificacion: "2400454852", nombres: "JOSEPH DEMIAN", apellidos: "DE LA CRUZ TIGRERO" },
        { identificacion: "0928017326", nombres: "DANIEL ALEJANDRO", apellidos: "DE LA CRUZ TOMALA" },
        { identificacion: "0928128370", nombres: "ANGEL DANIEL", apellidos: "DEL PEZO POZO" },
        { identificacion: "2400392417", nombres: "JULIO JOSE", apellidos: "DEL PEZO RODRIGUEZ" },
        { identificacion: "0928235381", nombres: "MADELINE ADRIANA", apellidos: "DOMINGUEZ VILLON" },
        { identificacion: "0928027333", nombres: "ANTHONY MICHAEL", apellidos: "ESCANDON ZAMBRANO" },
        { identificacion: "2450178161", nombres: "ELKIN ALESSANDRO", apellidos: "EUGENIO MENESES" },
        { identificacion: "0927261594", nombres: "ENRIQUE FABIAN", apellidos: "EUGENIO VERA" },
        { identificacion: "2450603051", nombres: "BRYAN CRISTOPHER", apellidos: "FRANCO REYES" },
        { identificacion: "2450670191", nombres: "GABRIEL ALBERTO", apellidos: "GOMEZ RAMIREZ" },
        { identificacion: "2450184011", nombres: "OSCAR JORDAN", apellidos: "GONZABAY MUÑOZ" },
        { identificacion: "0928700806", nombres: "ELKIN JAIR", apellidos: "GONZABAY SANTOS" },
        { identificacion: "0928020759", nombres: "JOSE DANIEL", apellidos: "GONZALEZ COCHEA" },
        { identificacion: "2450077983", nombres: "DANNY GABRIEL", apellidos: "GONZALEZ DE LA CRUZ" },
        { identificacion: "0941260085", nombres: "WILLIAN ALEXANDER", apellidos: "GONZALEZ GUIN" },
        { identificacion: "0928016377", nombres: "JEREMY JOSE", apellidos: "GONZALEZ LOOR" },
        { identificacion: "0941817991", nombres: "YOSTYN BYRON", apellidos: "GONZALEZ MEDINA" },
        { identificacion: "2450127259", nombres: "JOSEPH ANTHONY", apellidos: "GONZALEZ PERERO" },
        { identificacion: "2450880188", nombres: "STALYN JESUS", apellidos: "GONZALEZ RIVERA" },
        { identificacion: "2450834094", nombres: "RICARDO JOSUE", apellidos: "GONZALEZ VERA" },
        { identificacion: "2400161481", nombres: "ALEX ARIEL", apellidos: "GUALE MUÑOZ" },
        { identificacion: "0927960807", nombres: "CESAR DAVID", apellidos: "GUALE NEIRA" },
        { identificacion: "2450000555", nombres: "MAITE JAMILEX", apellidos: "GUALE ORRALA" },
        { identificacion: "0910106798", nombres: "WASHINGTON FABRICIO", apellidos: "HERNANDEZ ROCA" },
        { identificacion: "0930316443", nombres: "JAVIER ALONSO", apellidos: "INFANTE LOZANO" },
        { identificacion: "2400266173", nombres: "VICTOR ALEXIS", apellidos: "IZAGUIRRE POZO" },
        { identificacion: "1725995060", nombres: "MARCO IVAN", apellidos: "JACHO GUERRA" },
        { identificacion: "0942846502", nombres: "ESTALIN GABRIEL", apellidos: "JAEN GARCIA" },
        { identificacion: "0942811530", nombres: "ERICK ROLLER", apellidos: "JALCA CHALEN" },
        { identificacion: "2450090143", nombres: "JANDRY SANTIAGO", apellidos: "JAMA PITA" },
        { identificacion: "0928161223", nombres: "FREDDY EZEQUIEL", apellidos: "LAINEZ DEL PEZO" },
        { identificacion: "2450823097", nombres: "DIEGO ISAIAS", apellidos: "LAINEZ DOMINGUEZ" },
        { identificacion: "2400230351", nombres: "ELIZABETH MARLENE", apellidos: "LINDAO CHAVARRIA" },
        { identificacion: "2450296237", nombres: "JEAN CARLOS", apellidos: "LINO SANCHEZ" },
        { identificacion: "2400071813", nombres: "MARIA DE LOS ANGELES", apellidos: "LLERENA HERNANDEZ" },
        { identificacion: "2450534348", nombres: "MARISA ELIANA", apellidos: "MATIAS ALCIVAR" },
        { identificacion: "2450128257", nombres: "DIANA LUCIA", apellidos: "MELENA SANTANDER" },
        { identificacion: "2450320318", nombres: "RONALD SAMIR", apellidos: "MERA ORRALA" },
        { identificacion: "0942893389", nombres: "KERLLY BELINDA", apellidos: "MITE CHALEN" },
        { identificacion: "0953282639", nombres: "MIGUEL EDUARDO", apellidos: "MONTOYA ESPIN" },
        { identificacion: "2450591959", nombres: "SHEILY GABRIELA", apellidos: "MORAN PIGUAVE" },
        { identificacion: "0954714481", nombres: "JENNIFER AURORA", apellidos: "MUÑOZ GALABAY" },
        { identificacion: "2400187270", nombres: "JONATHAN STEVEN", apellidos: "MUÑOZ ROSALES" },
        { identificacion: "2450717943", nombres: "JAFET JAVAN", apellidos: "MURILLO DELGADO" },
        { identificacion: "0943604207", nombres: "ISAAC JACINTO", apellidos: "NICOLA SUAREZ" },
        { identificacion: "1755191150", nombres: "ANGEL SAUL", apellidos: "ORELLANA CONFORME" },
        { identificacion: "2450914664", nombres: "PAULO RAFAEL", apellidos: "ORRALA ARRIAGA" },
        { identificacion: "0927943084", nombres: "JOARKEL KENNETH", apellidos: "ORRALA CLEMENTE" },
        { identificacion: "2450060765", nombres: "PETER LEONARDO", apellidos: "ORRALA VILLON" },
        { identificacion: "2450075136", nombres: "NAYELI TATIANA", apellidos: "ORTEGA MATIAS" },
        { identificacion: "2400175226", nombres: "JOFFRE ANDRES", apellidos: "PALMA ROCAFUERTE" },
        { identificacion: "0928622471", nombres: "JONATHAN DAVID", apellidos: "PANCHANA RODRIGUEZ" },
        { identificacion: "0850903006", nombres: "RONALD DAVID", apellidos: "PARRAGA MENDOZA" },
        { identificacion: "2400094617", nombres: "DANIEL ALEJANDRO", apellidos: "PARRALES MERINO" },
        { identificacion: "1315679447", nombres: "CARLOS FERNANDO", apellidos: "PATIÑO GARCIA" },
        { identificacion: "1900583731", nombres: "SAID FAUSTO", apellidos: "PINTO TAMAYO" },
        { identificacion: "0926229030", nombres: "RICHARD LUIS", apellidos: "PIZARRO QUIMI" },
        { identificacion: "2450066754", nombres: "JOSE EDUARDO", apellidos: "PONCE CARLOS" },
        { identificacion: "0929549756", nombres: "VICTOR ANDRES", apellidos: "POVEDA BAIDAL" },
        { identificacion: "2400467565", nombres: "DEIVY ANTHONY", apellidos: "PRUDENTE MEREJILDO" },
        { identificacion: "0926462854", nombres: "STEEVEN ANDRES", apellidos: "PUERTAS MATIAS" },
        { identificacion: "2450929100", nombres: "JEREMY SHAIR", apellidos: "QUIMI ALAVA" },
        { identificacion: "2400249039", nombres: "ANDY WILFRIDO", apellidos: "QUIMI QUIMI" },
        { identificacion: "0942708264", nombres: "DAYRON ADRIAN", apellidos: "QUIÑONEZ VALENCIA" },
        { identificacion: "2450306432", nombres: "KEVIN JOEL", apellidos: "QUIRUMBAY TOMALA" },
        { identificacion: "2450753971", nombres: "KEVIN STEVEN", apellidos: "RAMIREZ GONZABAY" },
        { identificacion: "0940068968", nombres: "JEAN PIERRE", apellidos: "RAMIREZ TOMALA" },
        { identificacion: "2400310278", nombres: "ALISSON YAMEL", apellidos: "REYES RICARDO" },
        { identificacion: "2400194417", nombres: "OLGA ODALYS", apellidos: "RIVAS SALINAS" },
        { identificacion: "2450051459", nombres: "GIANLUIGGI FRANCISCO", apellidos: "RIVERA MONTENEGRO" },
        { identificacion: "2400240277", nombres: "DERLYS DANIEL", apellidos: "RIVERA REYES" },
        { identificacion: "0926914227", nombres: "YANDRIS MIGUEL", apellidos: "RIVERA TORRES" },
        { identificacion: "2400461386", nombres: "ARIANA NICOLE", apellidos: "ROCAFUERTE TOMALA" },
        { identificacion: "0928077007", nombres: "NICK MAURICIO", apellidos: "RODRIGUEZ BORBOR" },
        { identificacion: "2400183642", nombres: "JOEL STEVEN", apellidos: "RODRIGUEZ DE LA A" },
        { identificacion: "2450134347", nombres: "GABRIELA EVELYN", apellidos: "RODRIGUEZ GONZABAY" },
        { identificacion: "2450696139", nombres: "JOSE MOISES", apellidos: "RODRIGUEZ GUEVARA" },
        { identificacion: "2450724576", nombres: "ANDY WILLIAM", apellidos: "RUIZ MERA" },
        { identificacion: "2450365461", nombres: "DONATO ALEXANDER", apellidos: "SALAS MENDOZA" },
        { identificacion: "2450536236", nombres: "DAYWIN JOAN", apellidos: "SALVATIERRA COMANICHO" },
        { identificacion: "0925432155", nombres: "ERIK ALFREDO", apellidos: "SANCHEZ CASTRO" },
        { identificacion: "2400144743", nombres: "STEVEN ARIEL", apellidos: "SANCHEZ MITE" },
        { identificacion: "0952684926", nombres: "JOHN ZAIR", apellidos: "SANGURIMA SUAREZ" },
        { identificacion: "0942909227", nombres: "MELANNY YAMILETH", apellidos: "SOLORZANO PARRAGA" },
        { identificacion: "2400242521", nombres: "JEREMY GREGORIO", apellidos: "SUAREZ ÁVILA" },
        { identificacion: "2450219528", nombres: "ANGEL EDUARDO", apellidos: "SUAREZ RAMIREZ" },
        { identificacion: "2450739699", nombres: "DERLIS JORDAN", apellidos: "TAYLOR SANCHEZ" },
        { identificacion: "2450009580", nombres: "JOSE MANUEL", apellidos: "TIGRERO BENITEZ" },
        { identificacion: "2450356031", nombres: "ISABELA ODALYS", apellidos: "TIGRERO TIGRERO" },
        { identificacion: "0955074760", nombres: "CHARLES OSCAR", apellidos: "TOAZA TOMALA" },
        { identificacion: "0928160274", nombres: "INGRID MELISSA", apellidos: "TOMALA GONZALEZ" },
        { identificacion: "2450320433", nombres: "JUSTIN ARIEL", apellidos: "TOMALA GONZALEZ" },
        { identificacion: "0928235498", nombres: "DANIEL STEVEN", apellidos: "TOMALA LAINEZ" },
        { identificacion: "2450174533", nombres: "MELANIE ADRIANA", apellidos: "TOMALA MEREJILDO" },
        { identificacion: "2450618232", nombres: "AMY DAMARIS", apellidos: "TOMALA SILVESTRE" },
        { identificacion: "2450680893", nombres: "MIKE NEIMAN", apellidos: "TOMALA TUMBACO" },
        { identificacion: "0803570563", nombres: "DAMIAN JESUS", apellidos: "TORRES CADENA" },
        { identificacion: "0928160894", nombres: "EDGAR ARIEL", apellidos: "TUAREZ DE LA O" },
        { identificacion: "2450727207", nombres: "HENRY BRYAN", apellidos: "TUMBACO LINO" },
        { identificacion: "0504513565", nombres: "DAVID ISAIAS", apellidos: "UNAUCHO PONCE" },
        { identificacion: "2450463431", nombres: "DENIS STALYN", apellidos: "VACA ROSALES" },
        { identificacion: "0928238187", nombres: "LEONARDO JAIR", apellidos: "VALDIVIESO CLAVIJO" },
        { identificacion: "2350558694", nombres: "BYRON ANDRES", apellidos: "VELECELA MENDEZ" },
        { identificacion: "2450237694", nombres: "SAUL JOSHUE", apellidos: "VILLAO LOPEZ" },
        { identificacion: "0952465516", nombres: "SHIRLEY LILIAN", apellidos: "VILLON ALVARADO" },
        { identificacion: "0928029875", nombres: "ANGEL ALEJANDRO", apellidos: "VILLON PANIMBOZA" },
        { identificacion: "0928079169", nombres: "KATHERINE LISSETTE", apellidos: "VILLON SORIANO" },
        { identificacion: "2450866310", nombres: "PAUL SEBASTIAN", apellidos: "VIÑAN VALLEJO" },
        { identificacion: "2450336082", nombres: "LEONELA MARIEL", apellidos: "YAGUAL MEJILLON" },
        { identificacion: "0928860196", nombres: "MARLON BRANDO", apellidos: "ZAMBRANO SAAVEDRA" },
    ];

    for (let i = 0; i < estudiantesSoftware.length; i++) {
        const e = estudiantesSoftware[i];
        const created = await prisma.clientes.upsert({
            where: { clienteId: i + 1 },
            update: {
                email: 'yan2005dro@gmail.com',
            },
            create: {
                clienteId: i + 1,
                tipoIdentificacionId: 1, // CEDULA
                identificacion: e.identificacion,
                nombres: e.nombres,
                apellidos: e.apellidos,
                email: 'yan2005dro@gmail.com',
            },
        });
        clientes.push(created);
    }

  return clientes;
}
