# docker compose -f docker-compose.yml -f docker-compose.dev.yml up --build
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: jasrapo-backend-dev
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      NODE_ENV: development
      PORT: 3000
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
    restart: "no"
