services:
  # ─── Backend NestJS ─────────────────────────────
  - type: web
    name: jasrapo-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MINIO_ENABLED
        value: "false"
      - key: CORS_ORIGIN
        value: "*"
      - key: DATABASE_URL
        value: "postgresql://postgres:app_password_postgres@db.ducufrwisacuqhkhkohk.supabase.co:5432/postgres"
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
