allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  cpu-features: true
  esbuild: true
  prisma: true
  protobufjs: true
  ssh2: true
  unrs-resolver: true
