allowBuilds:
  '@nestjs/core': set this to true or false
  '@prisma/engines': set this to true or false
  '@scarf/scarf': set this to true or false
  bcrypt: set this to true or false
  cpu-features: set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
  protobufjs: set this to true or false
  ssh2: set this to true or false
  unrs-resolver: set this to true or false

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - cpu-features
  - esbuild
  - prisma
  - protobufjs
  - ssh2
  - unrs-resolver

overrides:
  rxjs: ^7.8.1
  crypto-js: ^4.2.0
  xmldom: npm:@xmldom/xmldom@^0.9.7
  protobufjs: ^8.2.0
  "@hono/node-server": ^1.19.13
  uuid: ^11.1.1
  path-to-regexp: ^8.3.0
  lodash: ^4.17.23
  handlebars: ^4.7.9
