// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from 'dotenv';
dotenv.config({ path: '../.env' });
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/schema/seed.ts',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
