name: Deploy Backend Only

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend only
        run: docker compose build backend

      - name: Deploy
        run: docker compose up -d
