name: Deploy Backend Only

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Backend
        uses: actions/checkout@v4

      - name: Deploy Backend Containers
        run: |
          docker compose up -d --build --remove-orphans

      - name: Limpieza de Docker
        run: |
          docker image prune -f
