name: Deploy Backend Only

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          clean: false

      - name: Build Backend only
        run: docker compose build backend --no-cache

      - name: Deploy
        run: docker compose up -d backend
