name: Update JASRAPO Repo

on:
  push:
    branches:
      - develop

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout JASRAPO
        uses: actions/checkout@v4
        with:
          repository: Brydyan/JASRAPO
          token: ${{ secrets.PAT }}

      - name: Update backend submodule
        run: |
          git submodule update --remote backend
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto update backend from develop"
          git push
